# Generated by Django 3.1.2 on 2021-08-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_tag_manager_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Google Tag Manager Enabled",
                    ),
                ),
                (
                    "google_tag_manager_container_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Google Tag Manager Container ID",
                    ),
                ),
                (
                    "google_analytics_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Google Analytics Enabled"
                    ),
                ),
                (
                    "google_analytics_property_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Google Analytics Property ID",
                    ),
                ),
                (
                    "google_analytics_view_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Google Analytics View ID",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={"verbose_name": "Analytics",},
        ),
    ]
