# Generated by Django 3.1.2 on 2021-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssettings",
            name="google_site_verification",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Google Site Verification",
            ),
        ),
    ]
