# Generated by Django 4.1.2 on 2022-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_analytics", "0002_analyticssettings_google_site_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssettings",
            name="plausible_enabled",
            field=models.BooleanField(default=False, verbose_name="Plausible Enabled"),
        ),
    ]
