# Generated by Django 4.1.3 on 2023-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_analytics", "0004_analyticssettings_plausible_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssettings",
            name="plausible_api_key",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Plausible API Key"
            ),
        ),
    ]
