# Generated by Django 4.1.3 on 2023-03-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_analytics", "0004_analyticssettings_plausible_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticssettings",
            name="google_analytics_view_id",
        ),
    ]
