# Generated by Django 4.1.3 on 2023-03-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_analytics", "0005_analyticssettings_plausible_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssettings",
            name="google_analytics_credentials_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="wagtail_analytics/lib/",
                verbose_name="Google Analytics Credentials File",
            ),
        ),
    ]
