# Generated by Django 4.1.3 on 2023-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_analytics", "0005_remove_analyticssettings_google_analytics_view_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssettings",
            name="google_analytics_measurement_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Google Analytics Measurement ID",
            ),
        ),
    ]
