# Generated by Django 4.1.3 on 2023-03-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_analytics",
            "0006_analyticssettings_google_analytics_credentials_file",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticssettings",
            name="google_analytics_credentials_file",
        ),
        migrations.RemoveField(
            model_name="analyticssettings",
            name="plausible_api_key",
        ),
    ]
